language: node_js
node_js:
- "11.10.1"
sudo: true
env:
  global:
  #s3_host
  - secure: KZTC+Y6qNh6PO2qQ7AwXI/sNUo8sHBknQkE3M+HwlbHkjq5OGunhTSk7AcQ+CcoAtYWuCJmP1nb7dk/Fq3d3AG8MtrnKqGEDbAF88Zt18BdlVkXvTez8Kl0D+iCW6IVW4P6/qxV6NLcf+0oEVF/kCL6DQ2UR5kP5D6JsiqsWJnh/Bzs49QzfmV7wTOQo7jAPGcR+VI4R7zGR3n2xHEZJkuIfM9GOLR6dokYLiJnxaQvUp1RjIs+ZDX2er+ksAQfrXkxb6PNmQvb1TPSaeDLQaG8Op6p7uRQsBdCULsOeqREinNCAMlIC0U7WMMIM3oYx9luhgDgV+XFJZr6n7YkoPxPpaFusBJ5dTH1Mmi6YsFZJixlT7PosfBvdKL4OzklVgdvpl/RtYkw6hdP8urVP9kR+WYjPSwqinRhEpYd2TYMXuNq3GV8VWZu7Ia/tAHiEzR+Nk3E6emKYXX++NzMqFl5zA+LsEeeitfKchz4K6w6labcHCNCtZefrJrgmN5SB8xl/gH33SDEgDUh2CLNUSKCtUsh47adEW69F/GuPPRpanTzwRYtosJxN6u6jmXVkbULmrv3TJheAsQXBMD+Yyb/IrcZFpwSZNWQY2OL6NSq59aiebGJgNtlal41bz+Ni21b2eb5Zsp3uTLNF8nth7/Uk/fbZjAJ0b3LfphXAy9g=
  #s3_access_key
  - secure: yrzl+1jZXIu/4y8QtKidY8+x8GUwVAWv4zcGnk2crLbmfkhHf0+Vm/xnV/NfPJg/bqpS6fuTq8v0+ScbVmqT8qqdIjsnOOvztSmKzfZIs5kW5tAgn47jw9Nl52VBNbsCokakDbVc99yLmLOfO5Bxj/+mpBXjYfpprnn3JzLgD0/PEGa0HbmQ8wx1lb2yQVlkKC8HPiTFv7EQO1RNifFa9aSiiN1SqlDP8Wsn+zhQfl3DX3qwbKQnliLUUWNzrryBABVOV73T+iidTou2E3vVeWqhFWt2P3bQAxjqgypI4gw2cYyoLdDVFp+aoAqQ2okV0wppU6DAjcZeO06TulSUyn9qnBUm0r6hdxlEOktxAlF2yKGB3G/TXMlermk0dvlKIlY39WY9yxlEeqSaZFig7/BVKbDpITjPlEQCd2kq2I9lD7MkqrayrW7m1RyRC40HBG4bGLajSSms4J/I/J9abDcv2VhjmkrVleHJyCTV2BPQSjopyuGXQeT2t1KPSLMPTeG/svxmmDkVQfbOP+TPFI7hi7LFc2tpGU4GfcwCowKfeoGv1m41aTwsyGwB/ztA7oaXLEjaVLQWimDBbkCUKOZbItpDqN/gzk0mrOkDu3bpjsAdj4p1cMN8wwBRHM2YMl+2fWifppZEvtLx3WJNWYVR/GY9FUkfyaOkY30r36Q=
  #s3_secret_key
  - secure: dR7vCgvEYFRWV2UTubFJNg36kbH2PYcoHv1wwUU1L9Q9Bo638ApqNIRuY3LqK120m4yokZhlVTbffpVA7cqeg40aRW4ZEsMkjmt2st3ni/OP7z2JDrFfmLHcFI4YG48uWLpAyKw0vtaqYeKprc3/5+U5WVPPo1QAxAd8fIi0gabBL4W3pDDp8WF9x2slvGGtMfggbBc1K3fTJ0ZDzR1YIcMsS337JikDMp8CSyMCIZZQr1mXiEBf2y7hWy2d2ve0hHgzCiRBWg9CnlPBmUery4pyHiNVUYiGx5p0mIQZJFdrbOQ7m+5865fRf/V8JgeC2A72/d+rt6gQI3V9IEuNHieaJNj/AeHWLnLR/G3+O6sOiswR1Ndo67HXOvBBMPxBNwbM6g6wqczIG3aMgMIMQiGVUTIMPbeEA1iR+LQdezoky6WW+TK0Pi8JMQa8lbnJ9F6CODZXfFbytsS/LJ1PQStrCaS3RPXFxAHI3MFvXsPPS9K7PamhdGiLKEyRLMP9whaRFkL8++N1FzmCsTAHYBsznN6Fai7cRnpZ0N+V2QfJBfoGFjJc+abN9t3bxYhTmeOTh7lIJrbWDe6Qi6mLxIDomqLw/2EfVBzHAXrQ7HpaAxLHWDOwKzPwqdsi2zkIsObW2zb63qboOH+TFWxiLXe6zxKAC88DNEJLVfzpLV0=
before_script: curl https://rclone.org/install.sh | sudo bash
jobs:
  include:
  - name: dev
    if: "(branch = master) or (tag =~ ^v)"
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    #- rclone copy dist :s3://auth/sdk/dev/ --s3-access-key-id="$S3_ACCESS_KEY" --s3-endpoint=$S3_HOST --s3-secret-access-key="$S3_SECRET_KEY"
    - rclone copy dist :s3://cdn-auth-super-com/authsdk/dev/ --s3-access-key-id=$AWS_CDN_ACCESS_KEY_ID --s3-secret-access-key=$AWS_CDN_ACCESS_SECRET_KEY --s3-region=eu-west-1
  - name: release
    if: "(tag =~ ^v)"
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    #- rclone copy dist :s3://auth/sdk/latest/ --s3-access-key-id="$S3_ACCESS_KEY" --s3-secret-access-key="$S3_SECRET_KEY" --s3-endpoint=$S3_HOST
    #- rclone copy dist :s3://auth/sdk/$TRAVIS_TAG/ --s3-access-key-id="$S3_ACCESS_KEY" --s3-secret-access-key="$S3_SECRET_KEY" --s3-endpoint=$S3_HOST
    - rclone copy dist :s3://cdn-auth-super-com/authsdk/latest/ --s3-access-key-id=$AWS_CDN_ACCESS_KEY_ID --s3-secret-access-key=$AWS_CDN_ACCESS_SECRET_KEY --s3-region=eu-west-1
    - rclone copy dist :s3://cdn-auth-super-com/authsdk/$TRAVIS_TAG/ --s3-access-key-id=$AWS_CDN_ACCESS_KEY_ID --s3-secret-access-key=$AWS_CDN_ACCESS_SECRET_KEY --s3-region=eu-west-1

notifications:
  email: false
  slack:
    secure: EfqPW3dwulj/+GsA3mMSTEAJGkt9XJ0YiapBHiiyfoVg0YToqto8st5LcJAhmQ+5XPyvnZ5fyZmOFQbYdLSV4JoZDx5AspObe2C0rM7mcdYA9JzTxseOr48XagZH2KOtf5+fgVuCANmfrxTv2xZAGC37hX9/YFdunG3SEvfmc1j1mSmwQqwDChsEDET6XzcgA/Q3tplLNcfLKXf2j4GR0Y1Lc+E6lsnRmRXeDVW6R9hI4rcfkCeSy+vWzAaa31t9i+O4zxZGcCxlTxKcbDVpBidCfu3pasbAjf+CCApfFNzEWRrfD7Wx77nrbdrUpta663YYB2gqU9/6dVLHbRCZIJMzc5KmAtrdxFC4kSf0V+g72oUXPe/0F6VxhJR68ymW8JZvWuiWCmfVqR4t3O90S1BXlL2Ccw5YOGs1NID6ZiPNn4XYBGp8LGpSqPgq/XCmJQgwYb7+ASZAj+P5EOjTrEHZJ01n/jxgRsmGxq6MYlFSywfeVxgRLL5ZJSTj1u05s+UadYtrUD6dN3dJaX+j5ZN/x4Su1FbT8KFKYzNmabQH9ireNzdvfZJkSPpxC1IByRB7LZWvDNCce0kCmqvBP9r7XVmRp7UNPIr2Zxyghq/6wGfxMTqZUN3vgJIqBwm+NumjbyIhAFFavBcRXlelVmL+khpNMof6X/DJ3n7fbG0=
